# Generated by Django 5.1.2 on 2024-11-14 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ocupacion', models.CharField(max_length=50)),
                ('verificado', models.BooleanField()),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='')),
                ('linkendin', models.CharField(max_length=100)),
                ('whatsapp', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Episodio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('duracion', models.CharField(max_length=50)),
                ('numero', models.IntegerField()),
                ('descripcion', models.CharField(max_length=200)),
                ('suscriptores', models.IntegerField()),
                ('likes', models.IntegerField()),
                ('comentarios', models.IntegerField()),
                ('anfitrion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.persona')),
            ],
        ),
    ]
